#import "cosmos/shaders/generation_utils.wgsl"::{
    GenerationParams,
    TerrainData,
    expand,
};

#import "cosmos/shaders/biosphere/grass.wgsl"::{
    generate as generate_0
};
#import "cosmos/shaders/biosphere/molten.wgsl"::{
    generate as generate_1
};
#import "cosmos/shaders/biosphere/ice.wgsl"::{
    generate as generate_2
};

const N_CHUNKS: u32 = 32;
const CHUNK_DIMENSIONS: u32 = 32;

@group(0) @binding(1) var<uniform> params: array<GenerationParams, N_CHUNKS>;
@group(0) @binding(2) var<uniform> chunk_count: u32;
@group(0) @binding(3) var<storage, read_write> values: array<TerrainData>;

@compute @workgroup_size(1024)
fn main(@builtin(global_invocation_id) invocation_id: vec3<u32>) {
    let idx = invocation_id.x;

    let coords = expand(idx, CHUNK_DIMENSIONS, CHUNK_DIMENSIONS, CHUNK_DIMENSIONS);
    if coords.w >= chunk_count {
        // Most times we won't be generating the full number of chunks we can at the same time, 
        // so exit early if we aren't generating this one.
        return;
    }

    let param = params[coords.w];

    // This will eventually be autogenerated
    switch param.biosphere_id.x {
        case 0u: {
            values[idx] = generate_0(param, coords);
            break;
        }
        case 1u: {
            values[idx] = generate_1(param, coords);
            break;
        }
        case 2u: {
            values[idx] = generate_2(param, coords);
            break;
        }
        default: {
            // If this happens, the biosphere may not have been registered properly
            break;
        }
    }
}
