package com.cornchipss.cosmos.biospheres;

import com.cornchipss.cosmos.registry.Biospheres;
import com.cornchipss.cosmos.structures.Structure;

/**
 * <p>A way of generating a planet's terrain</p>
 * <p>Register a biosphere by calling {@link Biospheres#registerBiosphere(Class, String)}</p>
 */
public abstract class Biosphere
{
	/**
	 * Generates a planet's terrain
	 * @param s The planet to generate
	 */
	public void generatePlanet(Structure s)
	{
		generateTerrain(s);
		populate(s);
	}
	
	/**
	 * Generates the base terrain everything should be based on
	 * @param s The planet to generate it on
	 */
	protected abstract void generateTerrain(Structure s);
	
	/**
	 * Used to populate the previously generated by {@link Biosphere#generateTerrain(Structure)}
	 * @param s The planet to populate
	 */
	protected abstract void populate(Structure s);
}